<?php

namespace RACDevelopment\ProductBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductStockOutgoingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductStockOutgoingRepository extends EntityRepository
{
}
