rac_development_product_stock_outgoing:
    resource: "@RACDevelopmentProductBundle/Resources/config/routing/product_stock_outgoing.yml"
    prefix: /admin/product/outgoing

rac_development_product_stock_incoming:
    resource: "@RACDevelopmentProductBundle/Resources/config/routing/product_stock_incoming.yml"
    prefix: /admin/product/incoming

rac_development_product_front:
    resource: "@RACDevelopmentProductBundle/Resources/config/routing/product_front.yml"
    prefix: /

rac_development_product:
    resource: "@RACDevelopmentProductBundle/Resources/config/routing/product.yml"
    prefix: /admin/product
